services:
  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: bot
    volumes:
      - ./src:/app/src
    restart: no
    env_file: .env

  redis:
    image: redis:8.4.0-alpine
    container_name: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
